Sprint1
ClevertecFrontendLab/sprint1-udulko2 pull request #1
Opened 2023-01-30 09:09 UTC by udulko2

2023-01-30 09:11 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675069896/content-window.png)

2023-01-30 09:28 UTC, dariavorom requested changes

2023-01-30 09:28 UTC, dariavorom commented on src/components/card/book-card.css
> +  /* white-space: nowrap; */
удалить весь закомментированный код в стилях и по проекту всему

2023-01-30 09:28 UTC, dariavorom commented on src/components/filter/filter-bar.jsx
> +    console.log(t);
console.log только для разработки, удалить все консольки

2023-01-30 09:28 UTC, dariavorom commented on src/components/filter/filter-bar.jsx
> +          <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
svg прямо в коде  - это не круто. импортируй сразу svg. сохрани в проект в папку в компонентом в папку assets и в компоненте импрортируй import { ReactComponent as Icon } from 'путь'
почитай об этом

2023-01-30 09:28 UTC, dariavorom commented on src/components/navigation/navigation.jsx
> +            <li className="nav-subitem nav-subitem-all"><Link to="/books/all" className="nav-sublink nav-sublink--active" onClick={(e) => selectSubitem(e)}>Все книги</Link></li>
такие однотипные элементы выводить через map

2023-01-30 09:28 UTC, dariavorom commented on src/components/navigation/navigation.jsx
> +  const selectItem = (e) => {
querySelector в реакте)
нет, тут нужен другой подход. есть ref, чтобы обратиться к элементу "по-реактовски", но в данном кейсе это не нужно. можно менять, стили, например, с помощью NavLink вместо Link. почитай об этом

2023-01-30 09:28 UTC, dariavorom commented on src/pages/main/main-page.jsx
> +      <Link to="/books/category/123"><BookCard title='Thinking in Java' author='Bruce Eckel' year='1998' /></Link>
тоже через map. создать переменные в данными в отдельной папке и выводить мапом

2023-01-30 09:28 UTC, dariavorom commented on src/components/filter/filter-bar.jsx
> +    const element = document.querySelector('.books-wrapper');
querySelector не надо здесь использовать. менять вид карточек с помощью useState. у нас все таки react приложение

2023-01-30 09:28 UTC, dariavorom commented on src/components/card/book-card.jsx
> +import './book-card.css';
пересмотри стили карточек, кнопка со звездами должны быть к низу на всех карточках одинаково
![image](https://user-images.githubusercontent.com/64946271/215438791-dfb9b3c4-6a64-4b63-a89b-7bd5403449ee.png)

2023-01-30 17:26 UTC, udulko2 commented on src/components/card/book-card.jsx
> +import './book-card.css';
справедливости ради, отмечу, что по макету, на списках, кнопка со звездами плавает вверх-вниз в зависимости от вышележащего контента. как бы делал по макету.
ну там расстояние между автором и кнопкой великоватое, это да, поправлю.

2023-01-30 17:28 UTC, udulko2 commented on src/pages/main/main-page.jsx
> +      <Link to="/books/category/123"><BookCard title='Thinking in Java' author='Bruce Eckel' year='1998' /></Link>
это понятно. просто зачем сейчас это делать, если на этом спринте основной упор на статику, верстку. 
на следующих спринтах будет интеграция с бэкендом, оттуда и будут прилетать данные, скорее всего будет массив, ну вот его и разложу через map.

2023-01-30 19:12 UTC, dariavorom commented on src/pages/main/main-page.jsx
> +      <Link to="/books/category/123"><BookCard title='Thinking in Java' author='Bruce Eckel' year='1998' /></Link>
Чтобы продемонстрировать знания, чтобы код был чище, а так же умение искать информацию и находить решение)

2023-01-30 19:13 UTC, dariavorom commented on src/components/card/book-card.jsx
> +import './book-card.css';
Тут согласна, на макете действительно разное расстояние. Тогда тут на твое усмотрение. На мой взгляд на одном расстоянии смотрится лучше.

2023-01-31 07:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675149198/content-window.png)

2023-01-31 07:14 UTC, udulko2 commented
залил. там всё: и знания, и читый код, и умение искать информацию, и находить решения)

2023-01-31 09:04 UTC, klichkovskiy requested changes

2023-01-31 09:04 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +            <h2>Рейтинг</h2>
Это же не заголовки. Просто текст

2023-01-31 09:04 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +            <h2>Подробная информация</h2>
Тоже самое. Далее по коду если есть исправь

2023-01-31 09:04 UTC, klichkovskiy commented on src/pages/main/main-page.jsx
> +        <Link to="/books/category/123"><BookCard title='Thinking in Java' author='Bruce Eckel' year='1998' /></Link>
промапай это

2023-01-31 09:12 UTC, dariavorom requested changes

2023-01-31 09:12 UTC, dariavorom commented on src/pages/main/main-page.jsx
> +        <Link to="/books/category/123"><BookCard title='Thinking in Java' author='Bruce Eckel' year='1998' /></Link>
да, я уже делала комментарий. неважно, что будет дальше, на этом спринте нету данных с бэка, поэтому нужно делать и практиковаться на том, что есть сейчас и учиться работать в команде)

2023-01-31 14:24 UTC, udulko2 commented on src/app.jsx
> +          <Route path='/oferta' element={<OfertaPage />} />
Ну они просто сейчас на этапе разработки заполнены одинаково, 
но строго говоря, по логике - это две разные страницы с абсолютно разным наполнением, с разной информацией, хотя и с идентичной стилистикой.
Как бы, предлагаю оставить.

2023-01-31 14:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/udulko2/1675175191/content-window.png)

2023-01-31 14:35 UTC, dariavorom approved these changes

2023-01-31 14:36 UTC, klichkovskiy approved these changes

2023-01-31 14:40 UTC, merged

2023-01-31 14:40 UTC, dariavorom commented
К следующему спринту порефакторь структуру в компонентах. В папке с компонентом отдельно папка assets с картинками, файлы называются, как компонент, кроме индексного и будет красота

2023-01-31 14:54 UTC, udulko2 commented
Такой вопрос.
На каждый следующий спринт буде отдельный проект? или новая ветка в этом?
Если до начала второго спринта коммитить сюда же (например в sprint1 или main), это ок?